name: cicd-aws-eb
run-name: ${{ github.actor }} is CICD pipeline from GitHub Actions AWS EB
env:
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SEC_KEY}}"
  AWS_ACCESS_KEY_ID    : "${{ secrets.AWS_ACCESS_KEY}}"
  PACKAGE_NAME         : "nodejs_app_${{ github.sha }}.zip"
  EB_APP_NAME          : "app_nodejs"
  EB_ENV_NAME          : "env-dev"
  EB_S3_NAME           : "githubaction-to-beanstalk"
  AWS_REGION           : "eu-central-1"

  
on: [push]
jobs:
  CI-step:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
    
    - name: Setup Node 
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Test npm
      run : echo "need run command whith npm"
      
    - name: Create ZIP package
      run : zip -r ${{ env.PACKAGE_NAME }} ./ -x *.git*
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }} 
        
    - name: Copy zip Deploymen package to S3 bucket
      run : aws s3 cp ${{ env.PACKAGE_NAME}} s3://${{ env.EB_S3_NAME}}/
      
    - name: Print msg 
      run : echo "CI-step finished"
    
  CD-step:
    runs-on: ubuntu-latest
    needs  : [CI-step]
    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Creation a new EB App version
      run : |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.EB_APP_NAME }} \
        --version-label "Ver-${{ github.run_id }}" \
        --description "Run by ${{ github.triggering_actor }} from ${{ github.repository }} ver-${{ github.run_id }}"
        --source-bundle S3Bucket="${{ env.EB_S3_NAME }}",S3Key="${{ env.PACKAGE_NAME }}" \

        
    - name: Deploy new version on AWS EB
      run : aws elasticbeanstalk update-environment --environment-name  ${{ env.EB_ENV_NAME }} --version-label "Ver-${{ github.run_id }}
      
    - name: Print msg in the end CD
      run : echo "CD step is finished successfully!"
  
     


